= Simplest blackbox tracing demo

This example is somewhat advanced because it performs initializations
for blackbox logging calls thoughout the program at the very beginning.
This makes it unnecessary to perform initializations on the first time
through. 
This is a small win in terms of time.
It also allows all the logging calls to be analyzed at program start
whether or not they are ever actually used.
This helps with identifying errors that might go unnoticed until
an erroneous logging call is used in an error situation.
So it helps to avoid the regret that comes from missing the data you 
needed to find the problem.

== Getting it running in 2024

The original used some Boost includes:

* `<boost/type_traits.hpp>` => `<type_traits>`
* `<boost/utility/enable_if.hpp>` => `<type_traits>`

Correspondingly, changed

* `boost::true_type` to `std::true_type`
* `boost::false_type` to `std::false_type`

Also

* `boost::disable_if_c` becomes `std::enable_if`, with the test negated.
* `boost::is_arithmetic` with `std::is_arithmetic`
* `boost::is_float` with `std::is_floating_point`
* `boost::is_same` with `std::is_same`
* `boost::is_enum` with `std::is_enum`
* `boost::is_array`` with `std::is_array`
* `boost::remove_const` with `std::remove_const`
* `boost::remove_bounds` with `std::remove_extent`
* `boost::is_pointer` with `std::is_pointer`

The exe wasn't working after fixing errors and warnings.
Possibly related to previously using 32-bit exe,
because I saw IMAGE_NT_HEADERS32.
Changing a couple of things to 64 allows the sections to be located.

Finally, fixing a simple error where it had been assumed that at least
one command-line argument was given allowed it to run.

== How to run

Run TraceTest.exe with no command line parameters to generate two 
files:

* `default.btra`: the blackbox file.
* `default.ttra`: output from scanning the logging calls, 
   used when interpreting the blackbox.

Then run Trace2Log in the same directory as the blackbox files, passing
`default` as the only command-line parameter.

The results are printed on the terminal.


